const title = document.querySelector(".titles");
const backColor = document.querySelector(".backGroundColor");
const list = document.querySelector("#listContainer");
const createForm = document.querySelector("#createForm");
const button = document.querySelector("#addButton");
button.addEventListener("click", (e) => {
  e.preventDefault();
  const container = document.createElement("div");
  const bigList = document.createElement("div");
  const smallList = document.createElement("div");
  const listForm = document.createElement("form");
  const newListTitle = document.createElement("span");
  const newListInput = document.createElement("input");
  const newListButton = document.createElement("button");
  const count = document.createElement("span");
  let countNumber = 0;
  count.innerText = countNumber;
  const listTitle = title.value;
  const color = backColor.value;
  container.id = "listContainer";
  listForm.id = "createBox";
  smallList.id = "contentBoxWrap";
  newListTitle.innerText = listTitle;
  newListTitle.style.backgroundColor = color;
  newListInput.id = "content";
  newListInput.type = "text";
  newListInput.placeholder = "새로 만들기";
  bigList.id = "firstList";
  newListButton.id = "addContent";
  newListButton.innerText = "추가";
  newListTitle.id = "listTitle";
  list.appendChild(container);
  container.appendChild(bigList);
  bigList.appendChild(newListTitle);
  bigList.appendChild(count);
  bigList.appendChild(smallList);
  bigList.appendChild(listForm);
  listForm.appendChild(newListInput);
  listForm.appendChild(newListButton);
  title.value = "";
  backColor.value = "";
  newListButton.addEventListener("click", (e) => {
    e.preventDefault();
    const newListContent = document.createElement("div");
    newListContent.innerText = newListInput.value;
    newListContent.id = "contentBox";
    smallList.appendChild(newListContent);
    newListInput.value = "";
    countNumber++;
    count.innerText = `${countNumber}`;
  });
});
